# Generated by Django 3.2.8 on 2022-07-20 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_auto_20220717_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='date_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 20, 13, 19, 16, 238359), null=True, verbose_name='Прибытие'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='date_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 20, 13, 19, 16, 238382), null=True, verbose_name='Выезд'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='nights',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='кол-во ночей'),
        ),
    ]
